using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Accounting.Infrastructure.Data.Migrations;

/// <summary>
/// Adds PostgreSQL sequences for invoice number generation.
/// Replaces the MAX+1 pattern which is not safe under concurrent creates.
///
/// Sequences are year-independent: the application prefixes the year.
/// START WITH 1 — safe to run on an existing database because the application
/// will use NEXTVAL which always returns a value ≥ 1; existing invoice numbers
/// are not affected (they were generated by the old MAX+1 logic).
/// </summary>
public partial class AddInvoiceSequences : Migration
{
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql("""
            CREATE SEQUENCE IF NOT EXISTS purchase_invoice_seq
                START WITH 1
                INCREMENT BY 1
                NO MINVALUE
                NO MAXVALUE
                CACHE 1;
            """);

        migrationBuilder.Sql("""
            CREATE SEQUENCE IF NOT EXISTS sales_invoice_seq
                START WITH 1
                INCREMENT BY 1
                NO MINVALUE
                NO MAXVALUE
                CACHE 1;
            """);

        // Advance sequences past the highest existing invoice numbers so that
        // the first generated number after migration does not collide with
        // any invoice created by the old MAX+1 logic.
        migrationBuilder.Sql("""
            DO $$
            DECLARE
                max_pur bigint;
                max_sal bigint;
            BEGIN
                SELECT COALESCE(MAX(
                    CASE
                        WHEN "InvoiceNumber" ~ '^PUR-[0-9]{4}-([0-9]+)$'
                        THEN CAST(SPLIT_PART("InvoiceNumber", '-', 3) AS bigint)
                        ELSE 0
                    END), 0)
                INTO max_pur
                FROM purchase_invoices;

                SELECT COALESCE(MAX(
                    CASE
                        WHEN "InvoiceNumber" ~ '^SAL-[0-9]{4}-([0-9]+)$'
                        THEN CAST(SPLIT_PART("InvoiceNumber", '-', 3) AS bigint)
                        ELSE 0
                    END), 0)
                INTO max_sal
                FROM sales_invoices;

                IF max_pur > 0 THEN
                    PERFORM SETVAL('purchase_invoice_seq', max_pur);
                END IF;

                IF max_sal > 0 THEN
                    PERFORM SETVAL('sales_invoice_seq', max_sal);
                END IF;
            END $$;
            """);
    }

    protected override void Down(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql("DROP SEQUENCE IF EXISTS purchase_invoice_seq;");
        migrationBuilder.Sql("DROP SEQUENCE IF EXISTS sales_invoice_seq;");
    }
}

